default: &default
  host: <%= ENV["DB_HOST"] || 'localhost' %>
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 10000
  database: reviewhunt_pre
  username: steemhunt

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 50